version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: time-tracker-db
    restart: always
    environment:
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: Drop348990
      POSTGRES_DB: timeTracker_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: